apiVersion: odin.cd-demo.io/v1
kind: TenantRouting
metadata:
  name: api-pulse
spec:
  services:
    - name: web
      k8sServicePrefix: api-pulse-web
      port: 80
      gatewayPath: /
    - name: auth
      k8sServicePrefix: api-pulse-auth
      port: 80
      gatewayPath: /auth
    - name: analytics
      k8sServicePrefix: api-pulse-analytics
      port: 80
      gatewayPath: /analytics
  global:
    web: latest
    auth: latest
    analytics: latest
  tenants:
    acme:
      web: 20260716-95eeb68
    globex: {}
