apiVersion: odin.cd-demo.io/v1
kind: TenantRouting
metadata:
  name: api-pulse
spec:
  services:
    - name: web
      k8sServicePrefix: api-pulse-web
      port: 80
      gatewayPath: /
    - name: auth
      k8sServicePrefix: api-pulse-auth
      port: 80
      gatewayPath: /auth
    - name: analytics
      k8sServicePrefix: api-pulse-analytics
      port: 80
      gatewayPath: /analytics
  global:
    web: 20260717-e1eddc8
    auth: 20260716-945376a
    analytics: 20260716-567591d
  tenants:
    acme: {}
    globex: {}
