apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odin
  namespace: argocd
spec:
  project: api-pulse
  source:
    repoURL: https://github.com/cd-demo/api-pulse-deploy.git
    targetRevision: main
    path: charts/odin
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: odin
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
