apiVersion: v1
kind: Secret
metadata:
  name: api-pulse-secrets
  labels:
    app.kubernetes.io/name: {{ include "api-pulse.name" . }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
{{- if and .Values.imagePullSecrets.enabled .Values.dockerHub.username .Values.dockerHub.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "api-pulse.name" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"https://index.docker.io/v1/":{"username":{{ .Values.dockerHub.username | quote }},"password":{{ .Values.dockerHub.password | quote }},"auth":{{ printf "%s:%s" .Values.dockerHub.username .Values.dockerHub.password | b64enc | quote }}}}
{{- end }}
